server:
  port: 9527
spring:
  application:
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh             #路由的ID，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://PAYMENT-SERVICE:8001    #匹配后提供服务的路由地址
          predicates:
            - Path=/Payment/selectById/**    #断言，路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://PAYMENT-SERVICE:8001
          predicates:
            - Path=/Payment/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka
