server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false   #自我保护机制，默认为true，不会立刻清除注册的服务
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


