server:
  port: 8001
spring:
  application:
    name: cloud-hystrix-payment8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
# 集群版     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: true
    fetch-registry: true